CREATE TABLE IF NOT EXISTS selecciones_catalogo (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  codigo_fifa TEXT NOT NULL UNIQUE,
  confederacion TEXT NOT NULL,
  escudo_url TEXT,
  bandera_url TEXT,
  ranking_fifa INTEGER CHECK (ranking_fifa IS NULL OR ranking_fifa > 0),
  ranking_puntos NUMERIC(10, 2),
  ranking_actualizado_en TIMESTAMPTZ,
  fifa_team_id TEXT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE equipos
  ADD COLUMN IF NOT EXISTS seleccion_catalogo_id INTEGER REFERENCES selecciones_catalogo(id) ON DELETE RESTRICT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_equipos_torneo_catalogo
  ON equipos (torneo_id, seleccion_catalogo_id)
  WHERE seleccion_catalogo_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_catalogo_selecciones_nombre ON selecciones_catalogo (nombre);
CREATE INDEX IF NOT EXISTS idx_catalogo_selecciones_ranking ON selecciones_catalogo (ranking_fifa);
